/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ermrspw;

import fungsi.akses;
import fungsi.koneksiDB;
import fungsi.sekuel;
import fungsi.validasi;
import java.awt.Color;
import java.awt.Dimension;
import static java.awt.image.ImageObserver.WIDTH;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Date;
import java.util.Properties;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import kepegawaian.DlgCariDokter;
import kepegawaian.DlgCariPegawai;
import kepegawaian.DlgCariPetugas;
import keuangan.Jurnal;
import rekammedis.RMCari5SOAPTerakhir;
import simrskhanza.DlgCariPasien;

/**
 *
 * @author GINANJAR
 */
public final class ERMrspw extends javax.swing.JFrame {

    private final DefaultTableModel tabModeSoap;
    private Connection koneksi = koneksiDB.condb();
    private sekuel Sequel = new sekuel();
    private validasi Valid = new validasi();
    private DlgCariPasien pasien = new DlgCariPasien(null, false);
    private DlgCariDokter dokter = new DlgCariDokter(null, false);
    public DlgCariPetugas petugas = new DlgCariPetugas(null, false);
    public DlgCariPegawai pegawai = new DlgCariPegawai(null, false);
    private RMCari5SOAPTerakhir soapterakhir = new RMCari5SOAPTerakhir(null, false);
    private PreparedStatement ps, ps2, ps3, ps4, ps5, ps6, pstindakan, psset_tarif, psrekening;
    private ResultSet rs, rstindakan, rsset_tarif, rsrekening;
    private int i = 0, jmlparsial = 0, jml = 0, index = 0, tinggi = 0;
    private String aktifkanparsial = "no", kode_poli = "", kd_pj = "", poli_ralan = "No", cara_bayar_ralan = "No",
            Suspen_Piutang_Tindakan_Ralan = "", Tindakan_Ralan = "", Beban_Jasa_Medik_Dokter_Tindakan_Ralan = "", Utang_Jasa_Medik_Dokter_Tindakan_Ralan = "",
            Beban_Jasa_Medik_Paramedis_Tindakan_Ralan = "", Utang_Jasa_Medik_Paramedis_Tindakan_Ralan = "", Beban_KSO_Tindakan_Ralan = "", Utang_KSO_Tindakan_Ralan = "",
            Beban_Jasa_Sarana_Tindakan_Ralan = "", Utang_Jasa_Sarana_Tindakan_Ralan = "", HPP_BHP_Tindakan_Ralan = "", Persediaan_BHP_Tindakan_Ralan = "",
            Beban_Jasa_Menejemen_Tindakan_Ralan = "", Utang_Jasa_Menejemen_Tindakan_Ralan = "";
    private final Properties prop = new Properties();
    private boolean[] pilih;
    private String[] kode, nama, kategori;
    private double[] totaltnd, bagianrs, bhp, jmdokter, jmperawat, kso, menejemen;
    private boolean sukses = false;
    private double ttljmdokter = 0, ttljmperawat = 0, ttlkso = 0, ttljasasarana = 0, ttlbhp = 0, ttlmenejemen = 0, ttlpendapatan = 0;
    private Jurnal jur = new Jurnal();

    public ERMrspw() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);

        tabModeSoap = new DefaultTableModel(null, new Object[]{
            "P", "No.Rawat", "No.R.M.", "Nama Pasien", "Perawatan/Tindakan", "Kode Dokter"}) {
            @Override
            public boolean isCellEditable(int rowIndex, int colIndex) {
                boolean a = false;
                if (colIndex == 0) {
                    a = true;
                }
                return a;
            }
            Class[] types = new Class[]{
                java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class,
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            @Override
            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }
        };
        table1.setModel(tabModeSoap);
        table1.setPreferredScrollableViewportSize(new Dimension(500, 500));
        table1.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textBox1 = new widget.TextBox();
        internalFrame1 = new widget.InternalFrame();
        panelBiasa1 = new widget.PanelBiasa();
        textBox2 = new widget.TextBox();
        TPasien = new widget.TextBox();
        label1 = new widget.Label();
        label3 = new widget.Label();
        cmbJam = new widget.ComboBox();
        cmbMnt = new widget.ComboBox();
        cmbDtk = new widget.ComboBox();
        DTPTgl = new widget.Tanggal();
        TNoRw = new widget.TextBox();
        textBox6 = new widget.TextBox();
        KdDok = new widget.TextBox();
        label4 = new widget.Label();
        label5 = new widget.Label();
        label6 = new widget.Label();
        label7 = new widget.Label();
        label8 = new widget.Label();
        label9 = new widget.Label();
        label10 = new widget.Label();
        label12 = new widget.Label();
        TNoRM = new widget.TextBox();
        TDokter = new widget.TextBox();
        label13 = new widget.Label();
        label14 = new widget.Label();
        TJk = new widget.TextBox();
        textBox11 = new widget.TextBox();
        textBox12 = new widget.TextBox();
        TJabatan = new widget.TextBox();
        label15 = new widget.Label();
        label16 = new widget.Label();
        panelBiasa3 = new widget.PanelBiasa();
        internalFrame2 = new widget.InternalFrame();
        PanelInput = new javax.swing.JPanel();
        ChkSoap = new widget.CekBox();
        ScrolSoap = new widget.ScrollPane();
        table1 = new widget.Table();
        internalFrame3 = new widget.InternalFrame();
        PanelICD = new javax.swing.JPanel();
        ChkIcd = new widget.CekBox();
        ScrolIcd = new widget.ScrollPane();
        table2 = new widget.Table();
        internalFrame4 = new widget.InternalFrame();
        PanelObt = new javax.swing.JPanel();
        ChkObt = new widget.CekBox();
        ScrolObt = new widget.ScrollPane();
        table3 = new widget.Table();
        panelBiasa4 = new widget.PanelBiasa();
        panelBiasa2 = new widget.PanelBiasa();

        textBox1.setText("textBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder("ERM-Rumah Sakit Putra Waspada"));
        internalFrame1.setLayout(new java.awt.BorderLayout());

        panelBiasa1.setPreferredSize(new java.awt.Dimension(1355, 150));
        panelBiasa1.setLayout(null);
        panelBiasa1.add(textBox2);
        textBox2.setBounds(590, 100, 290, 24);
        panelBiasa1.add(TPasien);
        TPasien.setBounds(590, 40, 290, 24);

        label1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label1.setText("No. Rawat");
        panelBiasa1.add(label1);
        label1.setBounds(510, 10, 60, 14);

        label3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label3.setText("Nama");
        panelBiasa1.add(label3);
        label3.setBounds(510, 40, 60, 14);

        cmbJam.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));
        cmbJam.setPreferredSize(new java.awt.Dimension(62, 28));
        cmbJam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmbJamKeyPressed(evt);
            }
        });
        panelBiasa1.add(cmbJam);
        cmbJam.setBounds(1550, 10, 62, 23);

        cmbMnt.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));
        cmbMnt.setPreferredSize(new java.awt.Dimension(62, 28));
        cmbMnt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmbMntKeyPressed(evt);
            }
        });
        panelBiasa1.add(cmbMnt);
        cmbMnt.setBounds(1620, 10, 62, 23);

        cmbDtk.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));
        cmbDtk.setPreferredSize(new java.awt.Dimension(62, 28));
        cmbDtk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmbDtkKeyPressed(evt);
            }
        });
        panelBiasa1.add(cmbDtk);
        cmbDtk.setBounds(1690, 10, 62, 23);

        DTPTgl.setForeground(new java.awt.Color(50, 70, 50));
        DTPTgl.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "24-11-2023" }));
        DTPTgl.setDisplayFormat("dd-MM-yyyy");
        DTPTgl.setOpaque(false);
        DTPTgl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                DTPTglKeyPressed(evt);
            }
        });
        panelBiasa1.add(DTPTgl);
        DTPTgl.setBounds(1450, 10, 90, 23);
        panelBiasa1.add(TNoRw);
        TNoRw.setBounds(590, 10, 180, 24);

        textBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textBox6ActionPerformed(evt);
            }
        });
        panelBiasa1.add(textBox6);
        textBox6.setBounds(1000, 10, 250, 24);
        panelBiasa1.add(KdDok);
        KdDok.setBounds(1000, 40, 70, 24);

        label4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label4.setText("Poliklinik");
        panelBiasa1.add(label4);
        label4.setBounds(930, 10, 50, 14);

        label5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label5.setText("Dokter");
        panelBiasa1.add(label5);
        label5.setBounds(930, 40, 50, 14);

        label6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label6.setText("Asuransi");
        panelBiasa1.add(label6);
        label6.setBounds(510, 100, 50, 14);

        label7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label7.setText(":");
        panelBiasa1.add(label7);
        label7.setBounds(990, 10, 10, 14);

        label8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label8.setText(":");
        panelBiasa1.add(label8);
        label8.setBounds(990, 40, 10, 14);

        label9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label9.setText(":");
        panelBiasa1.add(label9);
        label9.setBounds(580, 100, 10, 14);

        label10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label10.setText(":");
        panelBiasa1.add(label10);
        label10.setBounds(580, 40, 10, 14);

        label12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label12.setText(":");
        panelBiasa1.add(label12);
        label12.setBounds(580, 10, 10, 14);
        panelBiasa1.add(TNoRM);
        TNoRM.setBounds(780, 10, 100, 24);
        panelBiasa1.add(TDokter);
        TDokter.setBounds(1080, 40, 170, 24);

        label13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label13.setText("Jk/Umur");
        panelBiasa1.add(label13);
        label13.setBounds(510, 70, 60, 14);

        label14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label14.setText(":");
        panelBiasa1.add(label14);
        label14.setBounds(580, 70, 10, 14);
        panelBiasa1.add(TJk);
        TJk.setBounds(590, 70, 90, 24);
        panelBiasa1.add(textBox11);
        textBox11.setBounds(780, 70, 100, 24);
        panelBiasa1.add(textBox12);
        textBox12.setBounds(690, 70, 80, 24);
        panelBiasa1.add(TJabatan);
        TJabatan.setBounds(1000, 70, 250, 24);

        label15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label15.setText(":");
        panelBiasa1.add(label15);
        label15.setBounds(990, 70, 10, 14);

        label16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label16.setText("Spesialis");
        panelBiasa1.add(label16);
        label16.setBounds(930, 70, 50, 14);

        internalFrame1.add(panelBiasa1, java.awt.BorderLayout.PAGE_START);

        panelBiasa3.setBorder(javax.swing.BorderFactory.createTitledBorder("Riwayat Perawatan Pasien"));
        panelBiasa3.setPreferredSize(new java.awt.Dimension(500, 300));

        internalFrame2.setBorder(null);
        internalFrame2.setDoubleBuffered(false);
        internalFrame2.setLayout(new java.awt.BorderLayout());

        PanelInput.setPreferredSize(new java.awt.Dimension(200, 25));
        PanelInput.setLayout(new java.awt.BorderLayout());

        ChkSoap.setBackground(new java.awt.Color(51, 153, 255));
        ChkSoap.setForeground(new java.awt.Color(255, 255, 255));
        ChkSoap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/143.png"))); // NOI18N
        ChkSoap.setText("Riwayat SOAPIE");
        ChkSoap.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ChkSoap.setPreferredSize(new java.awt.Dimension(163, 25));
        ChkSoap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChkSoapActionPerformed(evt);
            }
        });
        PanelInput.add(ChkSoap, java.awt.BorderLayout.PAGE_START);

        ScrolSoap.setOpaque(true);

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        ScrolSoap.setViewportView(table1);

        PanelInput.add(ScrolSoap, java.awt.BorderLayout.CENTER);

        internalFrame2.add(PanelInput, java.awt.BorderLayout.PAGE_START);

        internalFrame3.setBorder(null);
        internalFrame3.setDoubleBuffered(false);
        internalFrame3.setLayout(new java.awt.BorderLayout());

        PanelICD.setPreferredSize(new java.awt.Dimension(200, 25));
        PanelICD.setLayout(new java.awt.BorderLayout());

        ChkIcd.setBackground(new java.awt.Color(51, 153, 255));
        ChkIcd.setForeground(new java.awt.Color(255, 255, 255));
        ChkIcd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/143.png"))); // NOI18N
        ChkIcd.setText("Diagnosa ICD");
        ChkIcd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ChkIcd.setPreferredSize(new java.awt.Dimension(163, 25));
        ChkIcd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChkIcdActionPerformed(evt);
            }
        });
        PanelICD.add(ChkIcd, java.awt.BorderLayout.PAGE_START);

        ScrolIcd.setOpaque(true);

        table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        ScrolIcd.setViewportView(table2);

        PanelICD.add(ScrolIcd, java.awt.BorderLayout.CENTER);

        internalFrame3.add(PanelICD, java.awt.BorderLayout.PAGE_START);

        internalFrame4.setBorder(null);
        internalFrame4.setDoubleBuffered(false);
        internalFrame4.setLayout(new java.awt.BorderLayout());

        PanelObt.setPreferredSize(new java.awt.Dimension(200, 25));
        PanelObt.setLayout(new java.awt.BorderLayout());

        ChkObt.setBackground(new java.awt.Color(51, 153, 255));
        ChkObt.setForeground(new java.awt.Color(255, 255, 255));
        ChkObt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/143.png"))); // NOI18N
        ChkObt.setText("Pemberian Obat");
        ChkObt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ChkObt.setPreferredSize(new java.awt.Dimension(163, 25));
        ChkObt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChkObtActionPerformed(evt);
            }
        });
        PanelObt.add(ChkObt, java.awt.BorderLayout.PAGE_START);

        ScrolObt.setOpaque(true);

        table3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        ScrolObt.setViewportView(table3);

        PanelObt.add(ScrolObt, java.awt.BorderLayout.CENTER);

        internalFrame4.add(PanelObt, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout panelBiasa3Layout = new javax.swing.GroupLayout(panelBiasa3);
        panelBiasa3.setLayout(panelBiasa3Layout);
        panelBiasa3Layout.setHorizontalGroup(
            panelBiasa3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(internalFrame2, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
            .addComponent(internalFrame3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(internalFrame4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelBiasa3Layout.setVerticalGroup(
            panelBiasa3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBiasa3Layout.createSequentialGroup()
                .addComponent(internalFrame2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(internalFrame3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(internalFrame4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        internalFrame1.add(panelBiasa3, java.awt.BorderLayout.LINE_START);

        panelBiasa4.setBorder(javax.swing.BorderFactory.createTitledBorder("Hasil Asesmen Terkini"));

        javax.swing.GroupLayout panelBiasa4Layout = new javax.swing.GroupLayout(panelBiasa4);
        panelBiasa4.setLayout(panelBiasa4Layout);
        panelBiasa4Layout.setHorizontalGroup(
            panelBiasa4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );
        panelBiasa4Layout.setVerticalGroup(
            panelBiasa4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 712, Short.MAX_VALUE)
        );

        internalFrame1.add(panelBiasa4, java.awt.BorderLayout.EAST);

        panelBiasa2.setBorder(javax.swing.BorderFactory.createTitledBorder("Form ERM"));

        javax.swing.GroupLayout panelBiasa2Layout = new javax.swing.GroupLayout(panelBiasa2);
        panelBiasa2.setLayout(panelBiasa2Layout);
        panelBiasa2Layout.setHorizontalGroup(
            panelBiasa2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 946, Short.MAX_VALUE)
        );
        panelBiasa2Layout.setVerticalGroup(
            panelBiasa2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 712, Short.MAX_VALUE)
        );

        internalFrame1.add(panelBiasa2, java.awt.BorderLayout.CENTER);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ChkSoapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChkSoapActionPerformed
        isSoap();
    }//GEN-LAST:event_ChkSoapActionPerformed

    private void ChkIcdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChkIcdActionPerformed
        isIcd();
    }//GEN-LAST:event_ChkIcdActionPerformed

    private void ChkObtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChkObtActionPerformed
        isObt();
    }//GEN-LAST:event_ChkObtActionPerformed

    private void cmbJamKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbJamKeyPressed

    }//GEN-LAST:event_cmbJamKeyPressed

    private void cmbMntKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbMntKeyPressed

    }//GEN-LAST:event_cmbMntKeyPressed

    private void cmbDtkKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbDtkKeyPressed

    }//GEN-LAST:event_cmbDtkKeyPressed

    private void DTPTglKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DTPTglKeyPressed

    }//GEN-LAST:event_DTPTglKeyPressed

    private void textBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textBox6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textBox6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ERMrspw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ERMrspw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ERMrspw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ERMrspw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ERMrspw().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.CekBox ChkIcd;
    private widget.CekBox ChkObt;
    private widget.CekBox ChkSoap;
    private widget.Tanggal DTPTgl;
    private widget.TextBox KdDok;
    private javax.swing.JPanel PanelICD;
    private javax.swing.JPanel PanelInput;
    private javax.swing.JPanel PanelObt;
    private widget.ScrollPane ScrolIcd;
    private widget.ScrollPane ScrolObt;
    private widget.ScrollPane ScrolSoap;
    private widget.TextBox TDokter;
    private widget.TextBox TJabatan;
    private widget.TextBox TJk;
    private widget.TextBox TNoRM;
    private widget.TextBox TNoRw;
    private widget.TextBox TPasien;
    private widget.ComboBox cmbDtk;
    private widget.ComboBox cmbJam;
    private widget.ComboBox cmbMnt;
    private widget.InternalFrame internalFrame1;
    private widget.InternalFrame internalFrame2;
    private widget.InternalFrame internalFrame3;
    private widget.InternalFrame internalFrame4;
    private widget.Label label1;
    private widget.Label label10;
    private widget.Label label12;
    private widget.Label label13;
    private widget.Label label14;
    private widget.Label label15;
    private widget.Label label16;
    private widget.Label label3;
    private widget.Label label4;
    private widget.Label label5;
    private widget.Label label6;
    private widget.Label label7;
    private widget.Label label8;
    private widget.Label label9;
    private widget.PanelBiasa panelBiasa1;
    private widget.PanelBiasa panelBiasa2;
    private widget.PanelBiasa panelBiasa3;
    private widget.PanelBiasa panelBiasa4;
    private widget.Table table1;
    private widget.Table table2;
    private widget.Table table3;
    private widget.TextBox textBox1;
    private widget.TextBox textBox11;
    private widget.TextBox textBox12;
    private widget.TextBox textBox2;
    private widget.TextBox textBox6;
    // End of variables declaration//GEN-END:variables

    private void isRawat() {
        Sequel.cariIsi("select reg_periksa.no_rkm_medis from reg_periksa where reg_periksa.no_rawat=? ", TNoRM, TNoRw.getText());
        //TCariPasien.setText(TNoRM.getText());
    }

    private void isPsien() {
        Sequel.cariIsi("select pasien.nm_pasien from pasien where pasien.no_rkm_medis=? ", TPasien, TNoRM.getText());
        Sequel.cariIsi("select if(pasien.jk = 'L', 'LAKI-LAKI','PEREMPUAN') from pasien where pasien.no_rkm_medis=? ", TJk, TNoRM.getText());
    }

    public void setNoRm(String norwt, Date tgl1, Date tgl2) {
        TNoRw.setText(norwt);
        //TCari.setText("");
        //DTPCari1.setDate(tgl1);
        //DTPCari2.setDate(tgl2);
        isRawat();
        isPsien();
        KdDok.setText(Sequel.cariIsi("select reg_periksa.kd_dokter from reg_periksa where reg_periksa.no_rawat=?", norwt));
        TDokter.setText(dokter.tampil3(KdDok.getText()));
//        KdDok2.setText(KdDok.getText());
//        KdDok3.setText(KdDok.getText());
//        TDokter2.setText(TDokter.getText()); 
//        TDokter3.setText(TDokter.getText()); 
//        ChkInput.setSelected(true);
//        isForm();
//        ChkInput1.setSelected(true);
//        isForm2();
//        ChkInput2.setSelected(true);
//        isForm3(); 
//        ChkInput3.setSelected(true);
//        isForm4();
//        TabRawatMouseClicked(null);
    }

    public void isCek() {
        if (akses.getjml2() >= 1) {
            KdDok.setText(akses.getkode());
            TDokter.setText(pegawai.tampil3(KdDok.getText()));
            TJabatan.setText(pegawai.tampilJbatan(KdDok.getText()));
        }
    }

    public void SetPoli(String KodePoli) {
        this.kode_poli = KodePoli;
    }

    public void SetPj(String KodePj) {
        this.kd_pj = KodePj;
    }

    private void isSoap() {
        if (ChkSoap.isSelected() == true) {
            ChkSoap.setVisible(false);
            PanelInput.setPreferredSize(new Dimension(WIDTH, 500));
            ScrolSoap.setVisible(true);
            ChkSoap.setVisible(true);

            ChkIcd.setSelected(false);
            PanelICD.setPreferredSize(new Dimension(WIDTH, 25));

            ChkObt.setSelected(false);
            PanelObt.setPreferredSize(new Dimension(WIDTH, 25));
        } else if (ChkSoap.isSelected() == false) {
            ChkSoap.setVisible(false);
            PanelInput.setPreferredSize(new Dimension(WIDTH, 25));
            ScrolSoap.setVisible(false);
            ChkSoap.setVisible(true);
        }
    }

    private void isIcd() {
        if (ChkIcd.isSelected() == true) {
            ChkIcd.setVisible(false);
            PanelICD.setPreferredSize(new Dimension(WIDTH, 500));
            ScrolIcd.setVisible(true);
            ChkIcd.setVisible(true);

            ChkSoap.setSelected(false);
            PanelInput.setPreferredSize(new Dimension(WIDTH, 25));

            ChkObt.setSelected(false);
            PanelObt.setPreferredSize(new Dimension(WIDTH, 25));
        } else if (ChkSoap.isSelected() == false) {
            ChkIcd.setVisible(false);
            PanelICD.setPreferredSize(new Dimension(WIDTH, 25));
            ScrolIcd.setVisible(false);
            ChkIcd.setVisible(true);
        }
    }

    private void isObt() {
        if (ChkObt.isSelected() == true) {
            ChkObt.setVisible(false);
            PanelObt.setPreferredSize(new Dimension(WIDTH, 500));
            ScrolObt.setVisible(true);
            ChkObt.setVisible(true);

            ChkSoap.setSelected(false);
            PanelInput.setPreferredSize(new Dimension(WIDTH, 25));

            ChkIcd.setSelected(false);
            PanelICD.setPreferredSize(new Dimension(WIDTH, 25));
        } else if (ChkObt.isSelected() == false) {
            ChkObt.setVisible(false);
            PanelObt.setPreferredSize(new Dimension(WIDTH, 25));
            ScrolObt.setVisible(false);
            ChkObt.setVisible(true);
        }
    }
}
